#ifndef C4C_TOKENS_H
#define C4C_TOKENS_H

#include "../../utils/include/utils.hpp"



std::string TOKEN_NAMES[] = {

    "TOKEN_EXP",
    "TOKEN_MUL",
    "TOKEN_DIV",
    "TOKEN_MOD",
    "TOKEN_ADD",
    "TOKEN_SUB",



    "TOKEN_GREATER",
    "TOKEN_LESS",
    "TOKEN_GREATER_EQUAL",
    "TOKEN_LESS_EQUAL",



    "TOKEN_EQUAL",
    "TOKEN_NOT_EQUAL",



    "TOKEN_BITWISE_AND",
    "TOKEN_BITWISE_OR",
    "TOKEN_BITWISE_XOR",
    "TOKEN_BITWISE_NOT",
    "TOKEN_LEFT_SHIFT",
    "TOKEN_RIGHT_SHIFT",



    "TOKEN_AND",
    "TOKEN_OR ",
    "TOKEN_NOT",


    "TOKEN_TERNARY",



    "TOKEN_PLUS_PLUS",
    "TOKEN_SUB_SUB",



    "TOKEN_ASSIGN",
    "TOKEN_ASSIGN_ADD",
    "TOKEN_ASSIGN_SUB",
    "TOKEN_ASSIGN_MUL",
    "TOKEN_ASSIGN_DIV",
    "TOKEN_ASSIGN_MOD",
    "TOKEN_ASSIGN_EXP",
    "TOKEN_ASSIGN_BITWISE_AND",
    "TOKEN_ASSIGN_BITWISE_OR",
    "TOKEN_ASSIGN_BITWISE_XOR",
    "TOKEN_ASSIGN_LEFT_SHIFT",
    "TOKEN_ASSIGN_RIGHT_SHIFT",




    "TOKEN_COLON",
    "TOKEN_TILDE",
    "TOKEN_RESOLUTION",
    "TOKEN_SEMI_COLON",
    "TOKEN_LBRACE",
    "TOKEN_RBRACE",
    "TOKEN_LBRACKET",
    "TOKEN_RBRACKET",
    "TOKEN_UNDERSCORE",
    "TOKEN_RETPARAM",
    "TOKEN_COMMA",
    "TOKEN_DOT",
    "TOKEN_AT",
    "TOKEN_TAB",
    "TOKEN_MULTI_COMMENT",
    "TOKEN_SINGLE_COMMENT",

    "TOKEN_IDENT",

    "TOKEN_LITERAL_INT",
    "TOKEN_LITERAL_FLOAT",
    "TOKEN_LITERAL_STRING",


    "TOKEN_KEYWORD_AND",
    "TOKEN_KEYWORD_ALLOC",
    "TOKEN_KEYWORD_AS",
    "TOKEN_KEYWORD_BREAK",
    "TOKEN_KEYWORD_BOOL",
    "TOKEN_KEYWORD_CASE",
    "TOKEN_KEYWORD_CAST",
    "TOKEN_KEYWORD_CHAR",
    "TOKEN_KEYWORD_CONST",
    "TOKEN_KEYWORD_CONTINUE",
    "TOKEN_KEYWORD_DEFAULT",
    "TOKEN_KEYWORD_DO",
    "TOKEN_KEYWORD_DEFER",
    "TOKEN_KEYWORD_ELIF",
    "TOKEN_KEYWORD_ELSE",
    "TOKEN_KEYWORD_ENUM",
    "TOKEN_KEYWORD_EXTERN",
    "TOKEN_KEYWORD_F32",
    "TOKEN_KEYWORD_F64",
    "TOKEN_KEYWORD_FALSE",
    "TOKEN_KEYWORD_FN",
    "TOKEN_KEYWORD_FOR",
    "TOKEN_KEYWORD_I8",
    "TOKEN_KEYWORD_I16",
    "TOKEN_KEYWORD_I32",
    "TOKEN_KEYWORD_I64",
    "TOKEN_KEYWORD_INCLUDE",
    "TOKEN_KEYWORD_IF",
    "TOKEN_KEYWORD_IMPL",
    "TOKEN_KEYWORD_LOOP",
    "TOKEN_KEYWORD_NATIVE",
    "TOKEN_KEYWORD_NEW",
    "TOKEN_KEYWORD_NOT_NEW",
    "TOKEN_KEYWORD_NOT",
    "TOKEN_KEYWORD_NULL",
    "TOKEN_KEYWORD_OR",
    "TOKEN_KEYWORD_PASS",
    "TOKEN_KEYWORD_PUB",
    "TOKEN_KEYWORD_REQUIRE",
    "TOKEN_KEYWORD_RETURN",
    "TOKEN_KEYWORD_SCOPED",
    "TOKEN_KEYWORD_SELF",
    "TOKEN_KEYWORD_SIZEOF",
    "TOKEN_KEYWORD_SIRI",
    "TOKEN_KEYWORD_STRUCT",
    "TOKEN_KEYWORD_SWITCH",
    "TOKEN_KEYWORD_TRUE",
    "TOKEN_KEYWORD_U8",
    "TOKEN_KEYWORD_U16",
    "TOKEN_KEYWORD_U32",
    "TOKEN_KEYWORD_U64",
    "TOKEN_KEYWORD_UNION",
    "TOKEN_KEYWORD_VOID",
    "TOKEN_KEYWORD_WHILE",
    "TOKEN_KEYWORD_WITH",


    "TOKEN_ERROR_INVALID_CHARACTER",            
    "TOKEN_ERROR_MALFORMED_NUMBER",
    "TOKEN_ERROR_UNTERMINATED_STRING",            
    "TOKEN_ERROR_UNTERMINATED_CHARACTER",
    "TOKEN_ERROR_INVALID_ESCAPE_CHARACTER",
    "TOKEN_ERROR_UNTERMINATED_COMMENT",
    "TOKEN_EOF",

  };



enum class TokenType
{

//   ARITHMETIC OPERATORS

    TOKEN_EXP = 0,
    TOKEN_MUL,
    TOKEN_DIV,
    TOKEN_MOD,
    TOKEN_ADD,
    TOKEN_SUB,

//  COMPARISON OPERATORS

    TOKEN_GREATER,
    TOKEN_LESS,
    TOKEN_GREATER_EQUAL,
    TOKEN_LESS_EQUAL,

//  EQUALITY OPERATORS

    TOKEN_EQUAL,
    TOKEN_NOT_EQUAL,

//  BITWISE OPERATORS

    TOKEN_BITWISE_AND,
    TOKEN_BITWISE_OR,
    TOKEN_BITWISE_XOR,
    TOKEN_BITWISE_NOT,
    TOKEN_LEFT_SHIFT,
    TOKEN_RIGHT_SHIFT,

//  LOGICAL OPERATORS

    TOKEN_AND,
    TOKEN_OR ,
    TOKEN_NOT,

//  TERNARY OPERATOR

    TOKEN_TERNARY,

//  INCREMENT OPERATORS

    TOKEN_PLUS_PLUS,
    TOKEN_SUB_SUB,

//  ASSIGNMENT OPERATORS

    TOKEN_ASSIGN,
    TOKEN_ASSIGN_ADD,
    TOKEN_ASSIGN_SUB,
    TOKEN_ASSIGN_MUL,
    TOKEN_ASSIGN_DIV,
    TOKEN_ASSIGN_MOD,
    TOKEN_ASSIGN_EXP,
    TOKEN_ASSIGN_BITWISE_AND,
    TOKEN_ASSIGN_BITWISE_OR,
    TOKEN_ASSIGN_BITWISE_XOR,
    TOKEN_ASSIGN_LEFT_SHIFT,
    TOKEN_ASSIGN_RIGHT_SHIFT,


//  MISCELLENIOUS SYMBOLS

    TOKEN_COLON,
    TOKEN_TILDE,
    TOKEN_RESOLUTION,
    TOKEN_SEMI_COLON,
    TOKEN_LBRACE,
    TOKEN_RBRACE,
    TOKEN_LBRACKET,
    TOKEN_RBRACKET,
    TOKEN_UNDERSCORE,
    TOKEN_RETPARAM,
    TOKEN_COMMA,
    TOKEN_DOT,
    TOKEN_AT,
    TOKEN_TAB,
    TOKEN_MULTI_COMMENT,
    TOKEN_SINGLE_COMMENT,

//  IDENTIFIERS

    TOKEN_IDENT,

//  LITERALS

    TOKEN_LITERAL_INT,
    TOKEN_LITERAL_FLOAT,
    TOKEN_LITERAL_STRING,

//  KEYWORDS

    TOKEN_KEYWORD_AND,
    TOKEN_KEYWORD_ALLOC,
    TOKEN_KEYWORD_AS,
    TOKEN_KEYWORD_BREAK,
    TOKEN_KEYWORD_BOOL,
    TOKEN_KEYWORD_CASE,
    TOKEN_KEYWORD_CAST,
    TOKEN_KEYWORD_CHAR,
    TOKEN_KEYWORD_CONST,
    TOKEN_KEYWORD_CONTINUE,
    TOKEN_KEYWORD_DEFAULT,
    TOKEN_KEYWORD_DO,
    TOKEN_KEYWORD_DEFER,
    TOKEN_KEYWORD_ELIF,
    TOKEN_KEYWORD_ELSE,
    TOKEN_KEYWORD_ENUM,
    TOKEN_KEYWORD_EXTERN,
    TOKEN_KEYWORD_F32,
    TOKEN_KEYWORD_F64,
    TOKEN_KEYWORD_FALSE,
    TOKEN_KEYWORD_FN,
    TOKEN_KEYWORD_FOR,
    TOKEN_KEYWORD_I8,
    TOKEN_KEYWORD_I16,
    TOKEN_KEYWORD_I32,
    TOKEN_KEYWORD_I64,
    TOKEN_KEYWORD_INCLUDE,
    TOKEN_KEYWORD_IF,
    TOKEN_KEYWORD_IMPL,
    TOKEN_KEYWORD_LOOP,
    TOKEN_KEYWORD_NATIVE,
    TOKEN_KEYWORD_NEW,
    TOKEN_KEYWORD_NOT_NEW,
    TOKEN_KEYWORD_NOT,
    TOKEN_KEYWORD_NULL,
    TOKEN_KEYWORD_OR,
    TOKEN_KEYWORD_PASS,
    TOKEN_KEYWORD_PUB,
    TOKEN_KEYWORD_REQUIRE,
    TOKEN_KEYWORD_RETURN,
    TOKEN_KEYWORD_SCOPED,
    TOKEN_KEYWORD_SELF,
    TOKEN_KEYWORD_SIZEOF,
    TOKEN_KEYWORD_SIRI,
    TOKEN_KEYWORD_STRUCT,
    TOKEN_KEYWORD_SWITCH,
    TOKEN_KEYWORD_TRUE,
    TOKEN_KEYWORD_U8,
    TOKEN_KEYWORD_U16,
    TOKEN_KEYWORD_U32,
    TOKEN_KEYWORD_U64,
    TOKEN_KEYWORD_UNION,
    TOKEN_KEYWORD_VOID,
    TOKEN_KEYWORD_WHILE,
    TOKEN_KEYWORD_WITH,

//  OTHERS

    TOKEN_ERROR_INVALID_CHARACTER,                 //done
    TOKEN_ERROR_MALFORMED_NUMBER,
    TOKEN_ERROR_UNTERMINATED_STRING,               //done
    TOKEN_ERROR_UNTERMINATED_CHARACTER,
    TOKEN_ERROR_INVALID_ESCAPE_CHARACTER,
    TOKEN_ERROR_UNTERMINATED_COMMENT,
    TOKEN_EOF,


};



class Tokens
{
public:
	TokenType type;
	std::string string;
	int start;
	int end;
	int row;
	int col;
	int line;

public:
	Tokens(TokenType type,std::string string,int start,int end,int row,int col,int line = 0)
	{
		this->type = type;
		this->string = string;
		this->start = start;
		this->end = end;
		this->line = line;
		this->row = row;
		this->col = col;
	}
	
	Tokens() = default;
	std::string get_type()
	{
		int type = static_cast<int>(this->type);
		return TOKEN_NAMES[type];
	}
	void print()
	{
		int type = static_cast<int>(this->type);
		std::cout << "  " <<  this->string << "    ==>    "  << TOKEN_NAMES[type] << std::endl;
		return;
	}

};

#endif
